(()=>{
const STYLE=`#messages .message{position:relative;touch-action:pan-y;-webkit-user-select:none;user-select:none;-webkit-touch-callout:none;align-self:flex-start!important;width:fit-content!important;max-width:min(78vw,520px)!important;min-width:0!important;overflow:visible}#messages .message.sent{align-self:flex-end!important}.msg-context{position:fixed;z-index:100000;display:none;min-width:250px;max-width:calc(100vw - 28px);padding:8px;background:#fff;border-radius:16px;box-shadow:0 8px 35px rgba(0,0,0,.22)}.msg-context.open{display:block}.msg-context button{border:0;background:transparent;border-radius:10px;padding:9px 11px;text-align:left;font-size:15px}.ctx-reactions{display:flex;gap:6px;padding:3px 2px 8px;border-bottom:1px solid #eee}.ctx-reactions button{font-size:22px;padding:5px}.ctx-actions{display:grid;grid-template-columns:1fr 1fr}.she-reply-quote{display:none!important}.she-edited{font-size:10px;opacity:.6;margin-left:4px}.she-reactions{display:flex;gap:3px;flex-wrap:wrap;position:absolute;right:7px;bottom:-10px;z-index:3}.message.received .she-reactions{left:7px;right:auto}.she-reaction-pill{border:1px solid rgba(0,0,0,.08);background:#fff;border-radius:12px;padding:2px 6px;font-size:13px;box-shadow:0 1px 4px rgba(0,0,0,.12)}.message.deleted .message-body{opacity:.65;font-style:italic}.swipe-reply-icon{position:absolute;left:-42px;top:50%;transform:translateY(-50%) scale(.7);opacity:0;width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:#078b59;color:#fff;font-size:17px}.message.swipe-ready .swipe-reply-icon{opacity:1;transform:translateY(-50%) scale(1)}
.chat-page .message-input-container{position:relative!important;display:flex!important;align-items:center!important;min-width:0!important;width:100%!important;overflow:hidden!important;box-sizing:border-box!important}
.chat-page .message-input-container .message-input{display:block!important;flex:1 1 auto!important;width:0!important;min-width:0!important;max-width:none!important;overflow-x:hidden!important;overflow-y:auto!important;white-space:pre-wrap!important;overflow-wrap:anywhere!important;word-break:break-word!important;box-sizing:border-box!important;padding-right:42px!important}
.chat-page .message-input-container #sendMessageButton,.chat-page .message-input-container #attachButton,.chat-page .message-input-container #cameraButton{position:absolute!important;top:50%!important;transform:translateY(-50%)!important;z-index:20!important;box-sizing:border-box!important;flex:none!important;height:38px!important;width:38px!important;min-width:38px!important;max-width:38px!important}
.chat-page .message-input-container #sendMessageButton{right:4px!important;flex-shrink:0!important}
.chat-page .message-input-container #attachButton,.chat-page .message-input-container #cameraButton{right:4px!important}
.chat-page .message-input-container #sendMessageButton.message-action-hidden{display:none!important}

/* Follow the phone/computer appearance setting automatically. No app preference or Firebase state is changed. */
@media (prefers-color-scheme:dark){
 body.chat-page{background:#111!important;color:#f5f5f5!important}
 body.chat-page .chat-app{background:#161616!important}
 body.chat-page .messages{background:linear-gradient(180deg,#181818 0%,#111 100%)!important;color:#f5f5f5!important}
 body.chat-page .received{background:#2b2b2b!important;color:#f5f5f5!important}
 body.chat-page .sent{background:linear-gradient(135deg,#1d6b42 0%,#185b39 100%)!important;color:#fff!important}
 body.chat-page .date-divider span{background:#2a2a2a!important;color:#ddd!important}
 body.chat-page .message-time-inline,body.chat-page .sent .message-time-inline{color:#b9b9b9!important}
 body.chat-page .typing-indicator{background:rgba(0,0,0,.25)!important;color:#ccc!important}
 body.chat-page .message-footer{background:#1a1a1a!important}
 body.chat-page .message-input-container{background:#242424!important;border-radius:24px!important}
 body.chat-page .message-input{color:#f5f5f5!important;caret-color:#fff!important}
 body.chat-page .message-input:empty::before{color:#999!important}
 body.chat-page .msg-context{background:#252525!important;color:#fff!important}
 body.chat-page .msg-context button{color:#fff!important}
 body.chat-page .ctx-reactions{border-bottom-color:#444!important}
 body.chat-page .she-reaction-pill{background:#303030!important;color:#fff!important;border-color:#555!important}
}
`;
let menu=null,pressTimer=null,startX=0,startY=0,swiping=false,moved=false,suppressClickUntil=0,firestoreUnsub=null,syncTimer=null;
const getText=el=>(el.querySelector('.message-body')?.innerText||el.innerText||'').replace(/\s+/g,' ').trim().slice(0,180);const getId=el=>el.dataset.messageId||el.getAttribute('data-message-id')||'';
function style(){if(document.getElementById('chatBubbleModernStyle'))return;const s=document.createElement('style');s.id='chatBubbleModernStyle';s.textContent=STYLE;document.head.appendChild(s)}
async function getFirebase(){try{const[cfg,app,authMod,fs]=await Promise.all([import('./firebase-config.js'),import('https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js')]);const apps=app.getApps();const firebaseApp=apps.length?apps[0]:app.initializeApp(cfg.firebaseConfig);return{auth:authMod.getAuth(firebaseApp),db:fs.getFirestore(firebaseApp),fs}}catch(e){return null}}
function conversationId(uid,other){return[uid,other].sort().join('_')}
async function syncMessageIdsAndState(){const container=document.getElementById('messages'),other=localStorage.getItem('currentChatUid');if(!container||!other)return;const x=await getFirebase(),uid=x?.auth?.currentUser?.uid;if(!x||!uid)return;const{collection,query,orderBy,onSnapshot}=x.fs;const cid=conversationId(uid,other),ref=collection(x.db,'conversations',cid,'messages'),q=query(ref,orderBy('createdAt','asc'));if(firestoreUnsub)firestoreUnsub();firestoreUnsub=onSnapshot(q,snapshot=>{const bubbles=[...container.querySelectorAll('.message')];snapshot.docs.forEach((docSnap,index)=>{const el=bubbles[index];if(!el)return;el.dataset.messageId=docSnap.id;renderMessageState(el,docSnap.data())});bindAll()},()=>{})}
function renderMessageState(el,message){if(!message)return;const body=el.querySelector('.message-body');if(!body)return;el.classList.toggle('deleted',!!message.deleted);const quote=body.querySelector('.she-reply-quote');if(quote)quote.remove();if(message.deleted){const p=body.querySelector('p');if(p)p.textContent='This message was deleted'}let edited=el.querySelector('.she-edited');if(message.edited&&!edited){edited=document.createElement('span');edited.className='she-edited';edited.textContent='edited';el.querySelector('.message-time-inline')?.appendChild(edited)}else if(!message.edited&&edited)edited.remove();let reactions=el.querySelector('.she-reactions'),values=Object.values(message.reactions||{});if(values.length){if(!reactions){reactions=document.createElement('div');reactions.className='she-reactions';el.appendChild(reactions)}reactions.innerHTML='';[...new Set(values)].forEach(emoji=>{const pill=document.createElement('span');pill.className='she-reaction-pill';pill.textContent=emoji;reactions.appendChild(pill)})}else if(reactions)reactions.remove()}
function reply(el){window.dispatchEvent(new CustomEvent('sheReplyToMessage',{detail:{id:getId(el),text:getText(el),element:el}}));const i=document.getElementById('messageInput');if(i){i.focus();i.placeholder=getText(el)?'Reply to: '+getText(el):'Reply';i.dataset.replyTo=getId(el)}}function react(el,emoji){window.dispatchEvent(new CustomEvent('sheReactToMessage',{detail:{id:getId(el),emoji,element:el}}))}function edit(el){const i=document.getElementById('messageInput');if(!i)return;i.value=getText(el);i.dataset.editingId=getId(el);i.focus();window.dispatchEvent(new CustomEvent('sheEditMessage',{detail:{id:getId(el),text:getText(el),element:el}}))}function del(el){if(!confirm('Delete this message?'))return;window.dispatchEvent(new CustomEvent('sheDeleteMessage',{detail:{id:getId(el),element:el}}))}function closeMenu(){menu?.remove();menu=null}
function openMenu(el,x,y){closeMenu();suppressClickUntil=Date.now()+900;menu=document.createElement('div');menu.className='msg-context open';menu.innerHTML='<div class="ctx-reactions"><button data-e="❤️">❤️</button><button data-e="😂">😂</button><button data-e="😮">😮</button><button data-e="😢">😢</button><button data-e="🙏">🙏</button><button data-e="👍">👍</button></div><div class="ctx-actions"><button data-a="reply">↩️ Reply</button><button data-a="edit">✏️ Edit</button><button data-a="delete">🗑️ Delete</button></div>';document.body.appendChild(menu);menu.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{react(el,b.dataset.e);closeMenu()});menu.querySelector('[data-a=reply]').onclick=()=>{reply(el);closeMenu()};menu.querySelector('[data-a=edit]').onclick=()=>{edit(el);closeMenu()};menu.querySelector('[data-a=delete]').onclick=()=>{del(el);closeMenu()};const r=menu.getBoundingClientRect();menu.style.left=Math.min(Math.max(8,x),innerWidth-r.width-8)+'px';menu.style.top=Math.min(Math.max(8,y),innerHeight-r.height-8)+'px'}
function startPress(el,x,y){clearTimeout(pressTimer);startX=x;startY=y;swiping=false;moved=false;pressTimer=setTimeout(()=>{if(!moved&&!swiping){navigator.vibrate?.(30);openMenu(el,startX,startY)}},550)}function cancelPress(){clearTimeout(pressTimer);pressTimer=null}
function bind(el){if(el.dataset.msgActions)return;el.dataset.msgActions='1';const icon=document.createElement('span');icon.className='swipe-reply-icon';icon.textContent='↩';el.prepend(icon);el.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();openMenu(el,e.clientX,e.clientY)},{passive:false});el.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;startPress(el,e.clientX,e.clientY)},{passive:true});el.addEventListener('pointermove',e=>{const dx=e.clientX-startX,dy=e.clientY-startY;if(Math.abs(dx)>12||Math.abs(dy)>12)moved=true;if(Math.abs(dx)>10&&Math.abs(dx)>Math.abs(dy)){swiping=true;cancelPress();const x=Math.max(0,Math.min(72,dx));el.style.transform=`translateX(${x}px)`;el.classList.toggle('swipe-ready',x>42)}},{passive:true});el.addEventListener('pointerup',e=>{cancelPress();if(swiping){if(e.clientX-startX>42)reply(el);el.style.transition='transform .16s ease';el.style.transform='translateX(0)';el.classList.remove('swipe-ready');setTimeout(()=>el.style.transition='',180)}},{passive:true});el.addEventListener('pointercancel',cancelPress,{passive:true});el.addEventListener('touchstart',e=>{const t=e.touches[0];if(t)startPress(el,t.clientX,t.clientY)},{passive:true});el.addEventListener('touchmove',e=>{const t=e.touches[0];if(!t)return;if(Math.abs(t.clientX-startX)>12||Math.abs(t.clientY-startY)>12)cancelPress()},{passive:true});el.addEventListener('touchend',cancelPress,{passive:true})}
function bindAll(){document.querySelectorAll('#messages .message').forEach(bind)}function init(){style();const r=document.getElementById('messages');if(!r)return;bindAll();new MutationObserver(()=>{bindAll();clearTimeout(syncTimer);syncTimer=setTimeout(syncMessageIdsAndState,120)}).observe(r,{childList:true,subtree:true});syncMessageIdsAndState()}
window.sheReplyBridgeInstalled=true;window.addEventListener('sheReplyToMessage',e=>{const d=e.detail||{},i=document.getElementById('messageInput');if(!i||!d.id)return;i.dataset.replyTo=d.id;i.dataset.replyText=d.text||'';i.setAttribute('data-reply-to',d.id);i.setAttribute('data-reply-text',d.text||'');i.focus()});document.addEventListener('click',e=>{if(Date.now()<suppressClickUntil)return;if(menu&&!menu.contains(e.target))closeMenu()});window.addEventListener('sheMessagesChanged',()=>{clearTimeout(syncTimer);syncTimer=setTimeout(syncMessageIdsAndState,150)});window.addEventListener('beforeunload',()=>firestoreUnsub?.());document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();})();
