/* WhatsApp-style voice note controller: hold to record, release to send, swipe up to lock. */
(() => {
  let recorder, chunks = [], stream, startedAt, timer, locked = false, audioBlob, audioUrl, audio, analyser, raf;
  const $ = s => document.querySelector(s), byId = id => document.getElementById(id);
  const footer = () => $('.message-footer'), standard = () => $('.message-input-container'), mic = () => byId('micButton'), ui = () => byId('voiceRecordingUI');
  function setup(){ const x=ui(); if(!x)return; x.innerHTML='<button class="vn-delete" aria-label="Delete">✕</button><button class="vn-play" aria-label="Play">▶</button><div class="vn-main"><div><span class="vn-dot"></span><span id="recordingTime">0:00</span></div><div class="vn-wave">'+Array(28).fill('<i></i>').join('')+'</div></div><button class="vn-pause" aria-label="Pause">Ⅱ</button><button class="vn-send" aria-label="Send">➤</button>'; x.querySelector('.vn-delete').onclick=discard; x.querySelector('.vn-play').onclick=()=>audio&&(audio.paused?audio.play():audio.pause()); x.querySelector('.vn-pause').onclick=togglePause; x.querySelector('.vn-send').onclick=send; }
  function showLocked(){setup(); locked=true; footer()?.classList.add('voice-locked'); if(standard())standard().style.display='none'; if(mic())mic().style.display='none'; if(ui())ui().style.display='flex';}
  function wave(){if(!analyser||!recorder||recorder.state==='inactive')return; const d=new Uint8Array(analyser.frequencyBinCount); analyser.getByteFrequencyData(d); const n=Math.max(1,Math.round(d.reduce((a,b)=>a+b,0)/d.length/255*56)); $('.vn-wave')?.querySelectorAll('i').forEach((b,i)=>b.classList.toggle('active',i<n)); raf=requestAnimationFrame(wave);}
  async function begin(){if(recorder&&recorder.state!=='inactive')return; try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}}); recorder=new MediaRecorder(stream,MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?{mimeType:'audio/webm;codecs=opus'}:{}); chunks=[]; recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data); recorder.onstop=()=>{audioBlob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'}); audioUrl=URL.createObjectURL(audioBlob); audio=new Audio(audioUrl); stream?.getTracks().forEach(t=>t.stop()); stream=null; cancelAnimationFrame(raf); if(!locked)send();}; recorder.start(100); startedAt=Date.now(); timer=setInterval(()=>{const e=byId('recordingTime');if(e){const s=Math.floor((Date.now()-startedAt)/1000);e.textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}},100); setup(); if(ui())ui().style.display='flex'; if(mic())mic().classList.add('recording'); const C=new(window.AudioContext||window.webkitAudioContext)(); analyser=C.createAnalyser(); analyser.fftSize=128; C.createMediaStreamSource(stream).connect(analyser); wave();}catch(e){window.showError?.('Microphone access denied');}}
  function release(){if(!recorder||recorder.state==='inactive')return; locked=false; recorder.stop(); clearInterval(timer); timer=null; mic()?.classList.remove('recording');}
  function lock(){if(!recorder||recorder.state==='inactive')return; showLocked(); mic()?.classList.remove('recording');}
  function togglePause(){if(!recorder)return;if(recorder.state==='recording')recorder.pause();else if(recorder.state==='paused')recorder.resume();}
  async function send(){if(!audioBlob)return; const blob=audioBlob; locked=false; footer()?.classList.remove('voice-locked'); if(standard())standard().style.display=''; if(mic())mic().style.display=''; if(ui())ui().style.display='none'; if(typeof window.sendAudioMessage==='function')await window.sendAudioMessage(blob); discard();}
  function discard(){if(recorder&&recorder.state!=='inactive')recorder.stop();clearInterval(timer);stream?.getTracks().forEach(t=>t.stop());stream=null;audioBlob=null;if(audioUrl)URL.revokeObjectURL(audioUrl);audio=null;locked=false;footer()?.classList.remove('voice-locked');if(standard())standard().style.display='';if(mic())mic().style.display='';if(ui())ui().style.display='none';}
  let down=false,y=0; const b=mic(); if(b){b.onpointerdown=e=>{down=true;y=e.clientY;b.setPointerCapture?.(e.pointerId);begin()};b.onpointermove=e=>{if(down&&y-e.clientY>55){down=false;lock()}};b.onpointerup=()=>{if(down){down=false;release()}};b.onpointercancel=()=>{if(down){down=false;discard()}};b.oncontextmenu=e=>e.preventDefault();}
})();